# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyous', '0003_extrainfopage_extra_title'),
        ('events', '0002_democalendarpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoCalendarPage',
        ),
        migrations.CreateModel(
            name='CalendarPage',
            fields=[
            ],
            options={
                'verbose_name': 'Calendar Demo',
                'indexes': [],
                'proxy': True,
            },
            bases=('joyous.calendarpage',),
        ),
    ]
