# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180310_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarpage',
            options={'verbose_name': 'Calendar'},
        ),
    ]
