# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('events', '0004_auto_20180310_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EventsIndexPage',
        ),
    ]
