# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('general', '0002_infrastrukturpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.wagtailcore.fields.StreamField((('Mitgliedsantrag', wagtail.wagtailcore.blocks.TextBlock()), ('Misc', wagtail.wagtailcore.blocks.TextBlock()), ('Protokoll', wagtail.wagtailcore.blocks.TextBlock())))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
