# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-31 17:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_dokumentepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('Mitgliedsantrag', wagtail.wagtailcore.blocks.RichTextBlock()), ('Misc', wagtail.wagtailcore.blocks.RichTextBlock()), ('Protokoll', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
    ]
